
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      namespace: order
      labels:
        app: delivery
    spec:
      serviceAccountName: aws-dynamo
      containers:
      - name: delivery
        image: 735542962543.dkr.ecr.eu-west-2.amazonaws.com/service-delivery:4a743df38eed9f34b1babd352548b421bc42adf3
        env: 
        - name: SERVICE_ADDRESS
          value: "80"
        - name: SERVICE_DYNAMOTABLENAME
          value: "ordering-app"
        - name: SERVICE_DYNAMOREGION
          value: "eu-west-2"
        - name: SERVICE_GRPCADDRESS
          value: ":50001"
        ports:
        - name: web
          containerPort: 80
        - name: grpc
          containerPort: 50001
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      tolerations:
      - operator: Exists
        effect: NoSchedule
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule